### ISSUE TITLE
Booting with root=/dev/sda causes / to be unavailable

### ISSUE THREAD

**Issue by rothgar** [coreos/coreos-baremetal#124]
I am PXE booting hardware and trying to mount the local disks as /. Following [the documentation](https://coreos.com/os/docs/latest/booting-with-pxe.html) causes the system to error out and not finish loading.
I have verified /dev/sda and /dev/sda1 exist (I've tried using both) and can mount them using cloud-config as described [here](https://coreos.com/os/docs/latest/mounting-storage.html)
I have tried reformatting the partitions to no avail. After boot the journal doesn't show any failure to mount /dev/sda but other services fail because disk paths don't exist.

Examples

`root : unable to stat /usr/share/baselayout/sudoers : Permission denied ; TTY=unknown ; PWD=/ ;`

`calico-node.service: Failed at step EXEC spawning /opt/bin/calicoctl: No such file or directory`

After booting I can see temp drives mounted using `mount` but `ls /` says permission denied. I can't sudo because the sudoers file does not exist as stated in the error above. Leaving root=/dev/sda off of the PXE boot successfully boots the system into a ram disk.

For clarification, I have tried with 835.13.0 and 1000.0.0 coreos iso images.

**Comment by dghubble** [comment]
So you're using a kernel arg root=/dev/sda1, a Cloud config, the system crashes to the emergency shell on boot and no journalctl logs for `coreos-cloudinit`. Can you share the cloud-config and `cat /proc/cmdline`?

There is an example of using `bootcfg` and Ignition (successor to CoreOS cloud-config) called `pxe-disk` under examples, which might be useful to you.
* https://github.com/coreos/coreos-baremetal/blob/master/examples/profiles/pxe-disk.json (see kernel args)
* https://github.com/coreos/coreos-baremetal/blob/master/examples/ignition/format-disk.yaml (YAML, which becomes Ignition JSON)

**Comment by dghubble** [comment]
cc @crawford

**Comment by rothgar** [comment]
It doesn't crash to an emergency shell. It boots but with failures. SSHing into the host has this motd

```
CoreOS stable (1000.0.0)
Update Strategy: No Reboots
Failed Units: 3
  calico-install.service
  generate-tls-keys.service
  kubernetes-install.service
```
and when I look into why the services fail it's all because paths are not available/accessible.

mount shows the disk mounted
```
mount | grep sda
/dev/sda on / type ext4 (rw,relatime,seclabel,stripe=64,data=ordered)
```
but it's still in a unusable state.

```
ls /
ls: cannot open directory /: Permission denied
```

```
cat /proc/cmdline
rootflags=rw mount.usrflags=ro initrd=/images/coreos-alpha/1000.0.0.cpio.gz cloud-config-url=http://cloud-init/tepo.yaml console=ttyS1,115200 root=/dev/sda BOOT_IMAGE=/images/coreos-alpha/1000.0.0.vmlinuz
```

It could very well be something I'm doing wrong but I have tried reformatting the drive, verifying the partitions exist with `fdisk -l` and can mount the drive to other locations. It only appears to be the kernel arg that causes the issue.

I originally looked into bootcfg but it did not look feature complete or at the very least was missing enough documentation to make me not want to use it.

**Comment by dghubble** [comment]
Try argument root=/dev/sda1. It should be a filesystem partition, not the device.

**Comment by rothgar** [comment]
I tried both /dev/sda and /dev/sda1 with the same result. I did not try a label or lvm volume. I didn't want to hard code blkids and don't want to label every drive just to try and mount it.

Is there somewhere I can get more logs about why/when this is failing? What service/script processes arguments in /proc/cmdline?

**Comment by dghubble** [comment]
You said the journal showed nothing, but just to be sure, you ran `journalctl _EXE=/usr/bin/coreos-cloudinit` right? Nothing? And that was so I could see your kernel cmdline args.

**Comment by dghubble** [comment]
Did you create a filesystem on your partition, as mentioned in the Installation section of the [doc](https://coreos.com/os/docs/latest/booting-with-pxe.html) you linked? What's `df -T` say? Btw, in the Ignition example, the disk is explicitly partitioned and an ext4 filesystem is created which is suitable.

**Comment by rothgar** [comment]
OK, I think I may have found my problem.

The old partition table had a boot (ext2) partition as sda1 but it was too small for the full / (512 Mb). I then cleared the partitions and tried /dev/sda and as you pointed out the mount devices needs to be a partition not disk. After opening this ticket I deleted both partitions, created sda1 but forgot to mkfs the filesystem.

So I suppose I have two other questions.

1. Is there a way to format/initialize the disk on first boot? I'm not sure I can trust what state a drive is in or what partitions exist during boot. I know cloud-init can format the drive but that would require I boot once without root= specified and then reboot again after the disk has been formatted. Is this possible with ignition?
 2. Are benefits for booting with root= vs running in a ramdisk documented anywhere? Originally I wanted root= specified to make sure /var/lib/docker had space for images but after mounting/formatting the drive via cloud-init it seems like that might be a better solution.

Thanks for the help

**Comment by crawford** [comment]
> 1. Is there a way to format/initialize the disk on first boot? I'm not sure I can trust what state a drive is in or what partitions exist during boot. I know cloud-init can format the drive but that would require I boot once without root= specified and then reboot again after the disk has been formatted. Is this possible with ignition?

This is one of Ignition's primary use cases. In fact, we even have [this example](https://coreos.com/ignition/docs/latest/examples.html#btrfs) in our docs. I think it will be easiest if you converted your cloud-configs to Ignition configs. You'll find that a lot of these first-boot-subsequent-boot problems just fall away.

**Comment by rothgar** [comment]
Thanks, I was looking through some of the [other examples](https://github.com/coreos/coreos-baremetal/blob/master/examples/ignition/k8s-master.yaml) so I'll probably look into it more going forward.

Besides RAM savings are there other advantages/disadvantages to using a disk instead of ram?

**Comment by dghubble** [comment]
I create a root filesystem partition and specify `root` in the PXE booting Kubernetes example because images were filling the RAM disk - when testing network booting Kubernetes locally in VMs, I give each machine 1GB of RAM. In general, I'd favor disk storage (plus the servers have disks already) and only run from RAM for quick verifications. Maybe for some specialized use cases you'd want the performance.
