### ISSUE TITLE
Allow Ignition templates to be created via the gRPC API

### ISSUE THREAD

**Issue by dghubble** [coreos/coreos-baremetal#157]
Users can create a new `Group` or `Profile`, but cannot add a new Ignition config. Something like:

    import "github.com/coreos/coreos-baremetal/bootcfg/client"
    import "github.com/coreos/coreos-baremetal/bootcfg/server/serverpb"
    ...

    cfg := &client.Config{
        Endpoints: endpoints,
    }
    client, err := client.New(cfg)
    client.Ignition.PutIgnition(ctx context.Context, in *serverpb.IgnitionPutRequest)

Changes to backing storage need to be made to support this.

**Comment by dghubble** [comment]
@joeatwork

**Comment by joeatwork** [comment]
Nice!
