### ISSUE TITLE
examples: Provision a Ceph cluster

### ISSUE THREAD

**Issue by dghubble** [coreos/coreos-baremetal#163]
Request from @brianredbeard

**Comment by joeatwork** [comment]
+1 cool!

**Comment by dghubble** [comment]
We have Torus reference clusters and a [tutorial](https://github.com/coreos/coreos-baremetal/blob/master/Documentation/torus.md) now.

**Comment by dghubble** [comment]
With Torus, there is less of a need to maintain a Ceph reference cluster.
