### ISSUE TITLE
represent groups as either all bytes or all structured

### ISSUE THREAD

**Issue by joeatwork** [coreos/coreos-baremetal#165]
Right now, the Group protocol buffer looks like this:
```
message Group {
  // machine readable Id
  string id = 1;
  // human readable name
  string name = 2;
  // Profile id
  string profile = 3;
  // Selectors to match machines
  map<string, string> selector = 4;
  // JSON encoded metadata
  bytes metadata = 5;
}
```

The "metadata" field is structured JSON, but the type can't see that. It might be nice to either have the whole group be JSON bytes (which would work fine) or the whole group be structured (and have metadata be a map<string,string>, or some type, or some variant of the two).

**Comment by dghubble** [comment]
See RichGroup

**Comment by joeatwork** [comment]
Discussed - a maybe "Validate the bytes in `metadata` is a better unit of work"
