### ISSUE TITLE
Make profiles kernel and initrd version agnostic 

### ISSUE THREAD

**Issue by joeatwork** [coreos/coreos-baremetal#167]
Right now, consumers constructing profiles won't know the appropriate versions and paths to CoreOS kernels and initrd images when constructing profiles, since that version is a detail of whatever is contained in the "/assets" of bootcfg. This could be fixed by
- Allowing clients to push assets to bootcfg using the RPC endpoint, or
- Allowing clients to push profiles without specifying the CoreOS version (either by using a template or by simply providing the correct default)
- Some other awesome solution

**Comment by dghubble** [comment]
Currently, this requires a machine Profile author to know which CoreOS PXE images are available at some endpoint on the network. `bootcfg` happens to serve assets as a convenience, but kernel and initrd can point anywhere. 

I'm not keen for `bootcfg` to become the official source for cached CoreOS images within a datacenter and would prefer a cache-proxy or CoreUpdate-like installation. So I don't think a gRPC API for pushing CoreOS images is the right fit.

Perhaps, a bootcfg deployment specifies an `ASSETS_HOME` which points to where CoreOS images are cached on the network. iPXE scripts generated by `bootcfg` can prefix the kernel and initrd in Profile definitions automatically. Some thought is required about how this should work for GRUB netboot configs and if end users are allowed to provide iPXE templates (a requested feature), in which case they're completely responsible for the contents.

This moves the choice about where images can be found from the Profile writer to the `bootcfg` deployer. Its still a separate responsibility to manage the set of PXE images. Concerning installs to disk, by default those are downloaded from CoreOS, so all the install images are available and any of the CoreOS PXE images will suffice

**Comment by joeatwork** [comment]
Sweet! Let's talk a bit about this when you get in!

**Comment by joeatwork** [comment]
Discussed offline - the workaround ("Just get the assets from someplace else") is simple and probably workable! Thanks again!

**Comment by dghubble** [comment]
Yep, we discussed. `bootcfg` *can* host any assets users drop in `/var/lib/bootcfg/assets`, which should be used mainly for development and small clusters. In larger production datacenters, users should specify the location of mirrored CoreOS images (perhaps on some nearby file servers for network performance) or point to the publicly hosted CoreOS images. It is up to the administrator to choose the image source which is specified in `Profiles`.
