### ISSUE TITLE
messagepb package is in a folder serverpb

### ISSUE THREAD

**Issue by joeatwork** [coreos/coreos-baremetal#168]
There is an odd behavior when trying to use grpc client objects. Consider the following test program.

```go
package bootstrap

import (
	"fmt"

	"github.com/coreos/coreos-baremetal/bootcfg/server/serverpb"
)

func printIt() {
	obj := serverpb.GroupPutRequest{}
	fmt.Printf("%v", obj)
}
```

```sh
importdemo.go:6: imported and not used: "github.com/coreos-inc/tectonic-installer/vendor/github.com/coreos/coreos-baremetal/bootcfg/server/serverpb" as messagepb
importdemo.go:10: undefined: serverpb in serverpb.GroupPutRequest
```

The workaround is to explicitly specify the package name in the import line, for example:

```go
import serverpb "github.com/coreos/coreos-baremetal/bootcfg/server/serverpb"
```

The imported module can be named `messagepb` or `serverpb` but should allow users to import it unaliased.

**Comment by dghubble** [comment]
Unaliased, it can be used with `messagepb`, the declared package name. I should update the folder name or package name to prevent confusion here.
