### ISSUE TITLE
Stop requiring Ignition templates to specify their rendered format

### ISSUE THREAD

**Issue by joeatwork** [coreos/coreos-baremetal#176]
JSON templates are really hard to write and maintain, so maybe we can remove support for them? Please close this if it sounds goofy, or comment and I'll remove JSON support.

**Comment by dghubble** [comment]
I left support for JSON Ignition templates for users who wish to use their own conversion tools to produce Ignition JSON. For example, someone might convert YAML files to JSON manually with a tool like [fuze](https://github.com/coreos/fuze) or maybe they prefer toml or some other format `bootcfg` doesn't support. On the other hand, I'm not aware of anyone relying on this.

I don't know that I'd call this a feature request. More of a removal.

**Comment by joeatwork** [comment]
Here's the feature associated with the request - accept YAML over the API without specifying the type, or using an id named `$SOMETHING.yaml` - it's definitely not a show stopper, there are other solutions (for example, we could try to parse an expanded template as both flavors, we could allow API clients to tell us explicitly what type their payload was, or we could just treat ids of the form `$SOMETHING.yaml` specially) but it seems like whenever you can accomodate a use case by cutting code/making an API simpler, it's a nice way to go.

On the other side of things, I'm not sure that fuze/toml/what-have-you is useful in our general case since the templates aren't legal YAML or legal JSON. In my case, I can't read and parse YAML and produce JSON, or generate JSON from programming language literals, because of constructs like the following in my template:

```
{{ if .ssh_authorized_keys }}
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        {{ range $element := .ssh_authorized_keys }}
        - {{$element}}
        {{end}}
{{end}}
```

Let's talk about this when we can :)

**Comment by dghubble** [comment]
Yeah, presently the file type is determined by the file extension. Perhaps the proposed `IgnitionTemplate` in #166 takes the file type or maybe it can be reliably inferred from the content.

The use case for fuze/toml/etc. is simply that the conversion to JSON is done out-of-band so a user can provide a raw legal JSON they've prepared however. Running it through the template is a NoOp so then it is just validated to be valid Ignition JSON. How valuable that flexibility is to people, I don't know.

You're right, in the standard case users are providing template contents (perhaps `.tmpl`) which render to YAML or JSON. They're not YAML or JSON upfront, so I agree it is weird those file extensions must be used.

**Comment by joeatwork** [comment]
Discussed - going to go with (something like)
```
		// Unmarshal YAML or JSON Ignition config
		cfg, jerr := ignition.Parse(buf.Bytes())
		if jerr != nil {
			if yerr := yaml.Unmarshal(buf.Bytes(), &cfg); yerr != nil {
				log.Errorf("error parsing JSON Ignition config: %v", yerr, jerr)
				http.NotFound(w, req)
				return
			}
		}

                // .. do great stuff with cfg
```

**Comment by crawford** [comment]
Implicitly determining the content type is only going to lead to frustration. Please use MIME types and/or file extensions (dictated by types) to determine the content. Here is the Ignition MIME registration: http://www.iana.org/assignments/media-types/application/vnd.coreos.ignition+json.

What if my valid Ignition config has a valid template in it and I don't intend for or expect it to be expanded? Pain.

**Comment by dghubble** [comment]
The Ignition templates for most clusters and all the example clusters are technically templates which render *to* Ignition so if their extension should probably change to `.tmpl`. I'm not aware of a template extension standard so I'll continue to be lenient about that extension.

However, if Ignition content is provided and the requested extension on FileStores is `.ign` or `.ignition` or a MIME type is specified, we can persist that information and skip the template rendering in that case. #188

**Comment by crawford** [comment]
I would suggest `foo.ign.tmpl` and `bar.yml.tmpl`.

**Comment by dghubble** [comment]
Close by #178
