### ISSUE TITLE
bootcfg/http: Stop showing the version hash at path /

### ISSUE THREAD

**Issue by dghubble** [coreos/coreos-baremetal#196]
Stop showing the version hash at HTTP /. If bootcfg were to be deployed at a public endpoint, the version could be used by attackers to find out-of-date deployments in the future. This was added after v0.3.0 in #174 for convenience, but should be removed before v0.4.0.

cc @chancez

**Comment by dghubble** [comment]
Closed by 53a97f2d1788b3181702b817fbddc936ca4c363c

**Comment by chancez** [comment]
👍
