### ISSUE TITLE
rkt: requested IP address not available in network: metal0 

### ISSUE THREAD

**Issue by dghubble** [coreos/coreos-baremetal#208]
In the [bootcfg with rktl](https://github.com/coreos/coreos-baremetal/blob/master/Documentation/getting-started-rkt.md) tutorial, users may get the error `stage1: failed to setup network: requested IP address "172.15.0.2" is not available in network: metal0` or the same with 172.15.0.3 when using dnsmasq as shown in the example. Our recommendation has been to garbage collect old pods (usually works) or use the `rkt-gc-force` script (nuclear option).

```
sudo rkt gc --grace-period=0
./scripts/rkt-gc-force             # sometimes needed
```

It sounds like the script can be removed when a release closes https://github.com/coreos/rkt/issues/2319.

**Comment by joeatwork** [comment]
Sadly, the rkt changes look like they've been moved to 1.8

**Comment by dghubble** [comment]
I'm not 100% sure the upstream issue is the cause. Perhaps I'm doing something wrong building or launching those pods. @iaguis

**Comment by iaguis** [comment]
I guess this happens if there's a pod that was assigned with that IP.

Fixing coreos/rkt#2319 will make regular-GC release the IP too (instead of having to run the force script).

@steveeJ?

**Comment by steveeJ** [comment]
The following cases will lead to this failure when running the example:

* consecutively without GC (expected case)
* after reboot without a prior GC (bug)

I'm working on this and will hopefully have a solution by tomorrow.

**Comment by dghubble** [comment]
@iaguis yes, we assign an IP for each run on the example setup, so gc is used between runs. @steveeJ that matches my anecdotal observations. With your solution we'd be able to remove the nuclear script, regular gc would be sufficient, reliably. Thanks guys.

**Comment by steveeJ** [comment]
@dghubble the fix has been in since rkt 1.7.0. This should be good to close.

**Comment by dghubble** [comment]
During some usability testing today, @sym3tri ran into the "stage1: failed to setup network: requested IP address "172.15.0.2" is not available in network: metal0" with a rkt 1.8 install. I tested upgrading from rkt 1.6 to 1.8 myself and also find this is still a problem. Worse, the `scripts/rkt-gc-force` (nuclear option) no longer works. It seems that `/var/run/netns` paths have changed and I'm not sure how to cleanup whatever is being created to return to a working state, even after reboots.

Perhaps these problems are just a carry-over from using rkt <= 1.6 and users trying it now won't experience this. We needed to remove old `var/run/netns/cni-*` entries to fix after upgrade.

    sudo ip netns delete cni-blah-blah

*So far*, running `rkt gc --grace-period=0` seems to be working alright, but I'm going to continue using the project (btw reboots too) for a while to be sure. Also, the `rkt-gc-force` script should remain in place for some time, because the rkt run commands in this project are unusuable without it below rkt 1.6 and folks won't upgrade immediately.

**Comment by joeatwork** [comment]
I'm having the same issue - debug information follows:
```
~/Desktop/coreos-baremetal (master)$ rkt version
rkt Version: 1.8.0
appc Version: 0.8.4
Go Version: go1.6.2
Go OS/Arch: linux/amd64
Features: -TPM
~/Desktop/coreos-baremetal (master)$ cat /etc/rkt/net.d/20-metal.conf 
{
  "name": "metal0",
  "type": "bridge",
  "bridge": "metal0",
  "isGateway": true,
  "ipMasq": true,
  "ipam": {
    "type": "host-local",
    "subnet": "172.15.0.0/16",
    "routes" : [ { "dst" : "0.0.0.0/0" } ]
   }
}
~/Desktop/coreos-baremetal (master)$ sudo rkt gc --grace-period=0
gc: moving pod "c0727587-d555-473f-b7e1-58d7941c58f1" to garbage
Garbage collecting pod "c0727587-d555-473f-b7e1-58d7941c58f1"
stage1 gc: error cleaning up cgroups: open subcgroup: no such file or directory
~/Desktop/coreos-baremetal (master)$ sudo rkt run --debug --insecure-options=image --net=metal0:IP=172.15.0.2 --mount volume=assets,target=/var/lib/bootcfg/assets --volume assets,kind=host,source=$PWD/examples/assets --mount volume=data,target=/var/lib/bootcfg --volume data,kind=host,source=$DATA docker://quay.io/coreos/bootcfg:f561b83647d1dc7b8cc75d5844b16812b4c7498a -- -address=0.0.0.0:8080 -rpc-address=0.0.0.0:8081 -log-level=debug
image: using image from local store for image name coreos.com/rkt/stage1-coreos:1.8.0
image: using image from local store for url docker://quay.io/coreos/bootcfg:f561b83647d1dc7b8cc75d5844b16812b4c7498a
stage0: Preparing stage1
stage0: Writing image manifest
stage0: Loading image sha512-53318877ee4516f00e8eba5d6e9dab9866bb2157ad5a8f63aaeceed074f4032a
stage0: Writing image manifest
stage0: Writing pod manifest
stage0: Setting up stage1
stage0: Wrote filesystem to /var/lib/rkt/pods/run/3ef39841-acd1-42d8-aca3-38e9cacdd9f7
stage0: Pivoting to filesystem /var/lib/rkt/pods/run/3ef39841-acd1-42d8-aca3-38e9cacdd9f7
stage0: Execing /init
networking: loading networks from /etc/rkt/net.d
networking: loading network metal0 with type bridge
stage1: failed to setup network
  └─error adding network "metal0"
    └─requested IP address "172.15.0.2" is not available in network: metal0
~/Desktop/coreos-baremetal (master)$ sudo ./scripts/rkt-gc-force 
gc: moving pod "3ef39841-acd1-42d8-aca3-38e9cacdd9f7" to garbage
Garbage collecting pod "3ef39841-acd1-42d8-aca3-38e9cacdd9f7"
stage1 gc: error cleaning up cgroups: open subcgroup: no such file or directory
successfully removed aci for image: "sha512-ea28190fcddc7c8450c9649ad83a05da0a6cb343532f363ee84caaacad025d27"
rm: 1 image(s) successfully removed
successfully removed aci for image: "sha512-53318877ee4516f00e8eba5d6e9dab9866bb2157ad5a8f63aaeceed074f4032a"
rm: 1 image(s) successfully removed
Cannot remove namespace file "/var/run/netns/cni": No such file or directory
```

The most interesting lines of output seem to be

    stage1 gc: error cleaning up cgroups: open subcgroup: no such file or directory
    Cannot remove namespace file "/var/run/netns/cni": No such file or directory

Could these errors indicate I've installed rkt incorrectly? There are systemd bits in the `init` directory rkt distribution that I didn't install anywhere.

**Comment by dghubble** [comment]
I left some containers running and rebooted. I was able to just `rkt gc --grace-period=0` and run containers bound to the same IPs again. So, tentatively, GC is working post-reboot, as long as you manually cleanup `/var/run/netns` when upgrading to rkt 1.7+ (poor upgrade experience, but workable).

Ideally we wouldn't need to explicitly GC since we're exiting pods, but I'm not familiar with the underpinnings of rkt's design here vs how Docker releases IPs. @steveeJ? As long as explicit GC'ing always works though, this issue could be closed.

**Comment by dghubble** [comment]
@steveeJ GC still has an issue which then prevents re-launching a pod with the same IP, which makes it difficult to do examples.

sudo rkt gc --grace-period=0gc: moving pod "eadd9461-b2f5-43df-a1b2-3c2d590e02dc" to garbage
Garbage collecting pod "eadd9461-b2f5-43df-a1b2-3c2d590e02dc"
stage1 gc: error cleaning up cgroups: open subcgroup: no such file or directory

Let's improve the `rkt-gc-force` nuclear clean script for now #238

**Comment by dghubble** [comment]
I have not needed the `rkt-gc-force` script since I last posted after upgrading to rkt 1.8.

**Comment by steveeJ** [comment]
@dghubble It has been two weeks so I consider this issue fixed and suggest you to close it.

**Comment by dghubble** [comment]
several folks have reported issues with this, even after reboots, deletion of the CNI definition, and gc'ing repeatedly. Its been an issue for nearly every new user we onboard into the development setup.

@steveeJ what's the backstory on this? Its becoming a major blocker using rkt for development examples.

**Comment by squat** [comment]
@steveeJ I tried garbage collecting a million different ways and have been garbage collecting rkt using `rkt-gc-force` after every invocation of `rkt run` but still could not get my container to bind to IPs 172.0.0.2-5. Every time I ran:
````
sudo rkt run quay.io/coreos/bootcfg:latest --net=metal0:IP=172.15.0.2 -- -version
````
I would get
````
image: using image from local store for image name coreos.com/rkt/stage1-coreos:1.13.0
image: using image from local store for image name quay.io/coreos/bootcfg:latest
stage0: Preparing stage1
stage0: Writing image manifest
stage0: Loading image sha512-5feb5265cb2f2a5d7bf8c6e4c6f73a3d849d73a86d159a11d163bbb924938bfe
stage0: Writing image manifest
stage0: Writing pod manifest
stage0: Setting up stage1
stage0: Wrote filesystem to /var/lib/rkt/pods/run/68b87595-882c-4bdf-b4bf-42d441bdb9de
stage0: Pivoting to filesystem /var/lib/rkt/pods/run/68b87595-882c-4bdf-b4bf-42d441bdb9de
stage0: Execing /init
networking: loading networks from /etc/rkt/net.d
networking: loading network metal0 with type bridge
stage1: failed to setup network
  └─error adding network "metal0"
    └─requested IP address "172.15.0.2" is not available in network: metal0
````

Finally, after following @dghubble's suggestion of umounting and then removing all the CNI's in `/var/run/netns`, I was able to run the container. It should be noting that no amount of garbage collecting would release that IP address until I finally cleaned that directory. Now, garbage collecting between rkt invocations using `rkt-gc-force` works.

**Comment by arianvp** [comment]
I still have this issue with `rkt 1.26`

**Comment by arianvp** [comment]
Hmm running `rkt gc` seems to have done the trick now

**Comment by dghubble** [comment]
@arianvp `scripts/devnet` create / destroy was written partially to cleanup just the relevant pods appropriately (rather than gc'ing everything). It also runs both matchbox and dnsmasq in systemd transient units so they're daemonized and logs can be viewed with journalctl more easily.

**Comment by dghubble** [comment]
I still get questions about this issue, it has no end.

I did add support to the `script/devnet` script to just use docker instead.
