### ISSUE TITLE
Partials for Ignition Templates

### ISSUE THREAD

**Issue by BugRoger** [coreos/coreos-baremetal#230]
The Ignition templates for different profiles often contain similar content. In order to dry up the templates and/or avoid additional preprocessors, it would be nice to be able to split the file into multiple parts.

I propose a structure like:
```
ignition/
├── _passwd.tmpl
├── master.yaml
└── node.yaml
```

And then reuse the partials using plain go template:

```
---
ignition_version: 1

{{template "_passwd" .ssh_authorized_keys}}
...
```

For this to work, the template rendering needs to be changed to read all templates and reference them by name, rather than passing the content around.

Obviously, this shouldn't evolve into a web framework but I would find this functionality really useful. What do you think? Are you open for such a contribution?

**Comment by dghubble** [comment]
Template rendering for configs (Ignition, Cloud-config, etc.) currently renders just the config file listed in the `Profile` matching to a request, by machine selectors. I've considered using template sets to enable those template blocks [templar](https://github.com/dghubble/templar/blob/master/templar.go), but I'm not eager to introduce that complexity yet. Ignition V2 will support referencing remote templates, merging, appending, and checksums so I'd like to wait to see how well it works to address concerns about repetition in configs.

Not every config type (grub, cloud-init, kickstart, future things) will have such rich features as Ignition so perhaps there is a case for it down the road.

**Comment by BugRoger** [comment]
Yeah, fair enough. 

Our workaround is to use preprocessors that generate the groups, profiles and templates for easier consumption by bootcfg - And save our sanity duplicating and configuring many servers in different roles. So in a way, we are back to the `config.yaml` that generates the groups. We have all that setup in a build process.

It really feels like this should be bootcfgs job though because I can almost discard it and use just the preprocessors instead and harden the config onto an webserver.

**Comment by dghubble** [comment]
Related #322
