### ISSUE TITLE
Switch to Logrus for logging

### ISSUE THREAD

**Issue by dghubble** [coreos/coreos-baremetal#233]
Improve logging support and flexibility with logrus. Add additional information to logs if possible.

**Comment by rothgar** [comment]
I'd like support for debug logging to show more than just the registered URL.

It would often be handy to know the following details in debug log output

What group id/file was matched based on the query. What profile was used and what ignition/cloud file was rendered as a result. I can only imagine with a large set of files for different deployments/configurations this would get very hard to track by hand (the current method).

**Comment by dghubble** [comment]
@rothgar info level logging will show detailed messages about mismatches w.r.t groups, profiles, and template files (Ignition/cloud/generic). Debug logging will additionally show each match to a requested resource.
