### ISSUE TITLE
duplicate dhcp leases when using bootcfg w/ dnsmasq

### ISSUE THREAD

**Issue by mark-casey** [coreos/coreos-baremetal#245]
I have a dhcp server on my network that I have access to view leases on, but I cannot reconfigure. I'm trying to use the coreos/dnsmasq image as a proxydhcp to work with the existing dhcp to point to the bootcfg service. I recognize that the issue I'm having may well be with the existing dhcp server, but I'm not sure where to go from here so I wanted to solicit ideas and see if this might be an issue that can be fixed outside of that existing server.

(I am on 10.101.0.94, which is a coreos box):
`core@localhost ~ $ docker run --net=host --rm --cap-add=NET_ADMIN quay.io/coreos/dnsmasq -d -q --dhcp-range=10.101.0.1,proxy,255.255.255.0 --enable-tftp --tftp-root=/var/lib/tftpboot --dhcp-userclass=set:ipxe,iPXE --pxe-service=tag:#ipxe,x86PC,"PXE chainload to iPXE",undionly.kpxe --pxe-service=tag:ipxe,x86PC,"iPXE",http://10.101.0.94:8080/boot.ipxe --log-queries --log-dhcp`  
`core@localhost ~/coreos-baremetal $ docker run -p 8080:8080 --rm -v $PWD/examples:/var/lib/bootcfg:Z -v $PWD/examples/groups/pxe-disk:/var/lib/bootcfg/groups:Z quay.io/coreos/bootcfg:v0.3.0 -address=0.0.0.0:8080 -log-level=debug
`

Note that I'm trying to use the pxe-disk example, not the pxe example the docs showed; I've inserted an ssh public key into pxe-disk.

- When these two containers are not running, the existing dhcp server gives out one lease for each host.
- When these two containers are running and hosts are not yet set to PXE-boot, the existing dhcp server still gives out one lease for each host.
- When these two containers are running and hosts are set to PXE-boot, the existing dhcp server shows 3 active leases per host after the PXE-boot attempt. Only hosts that attempted PXE-boot have 3 leases.

![image](https://cloud.githubusercontent.com/assets/1864831/16248052/7aac5de8-37d2-11e6-843d-0c06c039b1e6.png)

docker logs for dnsmasq container:

> dnsmasq: started, version 2.75 cachesize 150
> dnsmasq: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
> dnsmasq-dhcp: DHCP, proxy on subnet 10.101.0.1
> dnsmasq-tftp: TFTP root is /var/lib/tftpboot
> dnsmasq: reading /etc/resolv.conf
> dnsmasq: using nameserver 10.100.0.1#53
> dnsmasq: using nameserver 209.18.47.62#53
> dnsmasq: using nameserver 209.18.47.61#53
> dnsmasq: using nameserver 10.101.0.1#53
> dnsmasq: read /etc/hosts - 1 addresses
> dnsmasq-dhcp: 3540586537 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 3540586537 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 304876241 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 304876241 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 4021605202 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 4021605202 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 2054996026 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 2054996026 vendor class: PXEClient:Arch:00000:UNDI:002001
> dnsmasq-dhcp: 2054996026 PXE(enp2s0f0) 0c:c4:7a:7c:c0:3a proxy
> dnsmasq-dhcp: 2054996026 tags: enp2s0f0
> dnsmasq-dhcp: 2054996026 broadcast response
> dnsmasq-dhcp: 2054996026 sent size:  1 option: 53 message-type  2
> dnsmasq-dhcp: 2054996026 sent size:  4 option: 54 server-identifier  10.101.0.94
> dnsmasq-dhcp: 2054996026 sent size:  9 option: 60 vendor-class  50:58:45:43:6c:69:65:6e:74
> dnsmasq-dhcp: 2054996026 sent size: 17 option: 97 client-machine-id  00:00:00:00:00:00:00:00:00:00:00:0c:c4:7a...
> dnsmasq-dhcp: 2054996026 sent size: 45 option: 43 vendor-encap  06:01:03:0a:04:00:50:58:45:08:07:80:00:01...
> dnsmasq-dhcp: 2054996026 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 2054996026 vendor class: PXEClient:Arch:00000:UNDI:002001
> dnsmasq-dhcp: 2054996026 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 2054996026 vendor class: PXEClient:Arch:00000:UNDI:002001
> dnsmasq-dhcp: 2054996026 PXE(enp2s0f0) 10.101.0.83 0c:c4:7a:7c:c0:3a undionly.kpxe.0
> dnsmasq-dhcp: 2054996026 tags: enp2s0f0
> dnsmasq-dhcp: 2054996026 bootfile name: undionly.kpxe.0
> dnsmasq-dhcp: 2054996026 next server: 10.101.0.94
> dnsmasq-dhcp: 2054996026 sent size:  1 option: 53 message-type  5
> dnsmasq-dhcp: 2054996026 sent size:  4 option: 54 server-identifier  10.101.0.94
> dnsmasq-dhcp: 2054996026 sent size:  9 option: 60 vendor-class  50:58:45:43:6c:69:65:6e:74
> dnsmasq-dhcp: 2054996026 sent size: 17 option: 97 client-machine-id  00:00:00:00:00:00:00:00:00:00:00:0c:c4:7a...
> dnsmasq-dhcp: 2054996026 sent size:  7 option: 43 vendor-encap  47:04:80:00:00:00:ff
> dnsmasq-tftp: error 0 TFTP Aborted received from 10.101.0.83
> dnsmasq-tftp: failed sending /var/lib/tftpboot/undionly.kpxe.0 to 10.101.0.83
> dnsmasq-tftp: sent /var/lib/tftpboot/undionly.kpxe.0 to 10.101.0.83
> dnsmasq-dhcp: 3144373782 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 3144373782 vendor class: PXEClient:Arch:00000:UNDI:002001
> dnsmasq-dhcp: 3144373782 user class: iPXE
> dnsmasq-dhcp: 3144373782 PXE(enp2s0f0) 0c:c4:7a:7c:c0:3a proxy
> dnsmasq-dhcp: 3144373782 tags: ipxe, enp2s0f0
> dnsmasq-dhcp: 3144373782 broadcast response
> dnsmasq-dhcp: 3144373782 sent size:  1 option: 53 message-type  2
> dnsmasq-dhcp: 3144373782 sent size:  4 option: 54 server-identifier  10.101.0.94
> dnsmasq-dhcp: 3144373782 sent size:  9 option: 60 vendor-class  50:58:45:43:6c:69:65:6e:74
> dnsmasq-dhcp: 3144373782 sent size: 17 option: 97 client-machine-id  00:00:00:00:00:00:00:00:00:00:00:0c:c4:7a...
> dnsmasq-dhcp: 3144373782 sent size: 28 option: 43 vendor-encap  06:01:03:0a:04:00:50:58:45:08:07:80:01:01...
> dnsmasq-dhcp: 3144373782 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 3144373782 vendor class: PXEClient:Arch:00000:UNDI:002001
> dnsmasq-dhcp: 3144373782 user class: iPXE
> dnsmasq-dhcp: 0 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 0 vendor class: PXEClient:Arch:00000:UNDI:002001
> dnsmasq-dhcp: 0 user class: iPXE
> dnsmasq-dhcp: 0 PXE(enp2s0f0) 10.101.0.90 0c:c4:7a:7c:c0:3a http://10.101.0.94:8080/boot.ipxe.0
> dnsmasq-dhcp: 0 tags: ipxe, enp2s0f0
> dnsmasq-dhcp: 0 bootfile name: http://10.101.0.94:8080/boot.ipxe.0
> dnsmasq-dhcp: 0 next server: 10.101.0.94
> dnsmasq-dhcp: 0 broadcast response
> dnsmasq-dhcp: 0 sent size:  1 option: 53 message-type  5
> dnsmasq-dhcp: 0 sent size:  4 option: 54 server-identifier  10.101.0.94
> dnsmasq-dhcp: 0 sent size:  9 option: 60 vendor-class  50:58:45:43:6c:69:65:6e:74
> dnsmasq-dhcp: 0 sent size: 17 option: 97 client-machine-id  00:00:00:00:00:00:00:00:00:00:00:0c:c4:7a...
> dnsmasq-dhcp: 0 sent size:  7 option: 43 vendor-encap  47:04:80:01:00:00:ff
> dnsmasq-dhcp: 2055027002 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 2055027002 vendor class: PXEClient:Arch:00000:UNDI:002001
> dnsmasq-dhcp: 2055027002 PXE(enp2s0f0) 0c:c4:7a:7d:39:3a proxy
> dnsmasq-dhcp: 2055027002 tags: enp2s0f0
> dnsmasq-dhcp: 2055027002 broadcast response
> dnsmasq-dhcp: 2055027002 sent size:  1 option: 53 message-type  2
> dnsmasq-dhcp: 2055027002 sent size:  4 option: 54 server-identifier  10.101.0.94
> dnsmasq-dhcp: 2055027002 sent size:  9 option: 60 vendor-class  50:58:45:43:6c:69:65:6e:74
> dnsmasq-dhcp: 2055027002 sent size: 17 option: 97 client-machine-id  00:00:00:00:00:00:00:00:00:00:00:0c:c4:7a...
> dnsmasq-dhcp: 2055027002 sent size: 45 option: 43 vendor-encap  06:01:03:0a:04:00:50:58:45:08:07:80:00:01...
> dnsmasq-dhcp: 2055027002 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 2055027002 vendor class: PXEClient:Arch:00000:UNDI:002001
> dnsmasq-dhcp: 2055027002 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 2055027002 vendor class: PXEClient:Arch:00000:UNDI:002001
> dnsmasq-dhcp: 2055027002 PXE(enp2s0f0) 10.101.0.82 0c:c4:7a:7d:39:3a undionly.kpxe.0
> dnsmasq-dhcp: 2055027002 tags: enp2s0f0
> dnsmasq-dhcp: 2055027002 bootfile name: undionly.kpxe.0
> dnsmasq-dhcp: 2055027002 next server: 10.101.0.94
> dnsmasq-dhcp: 2055027002 sent size:  1 option: 53 message-type  5
> dnsmasq-dhcp: 2055027002 sent size:  4 option: 54 server-identifier  10.101.0.94
> dnsmasq-dhcp: 2055027002 sent size:  9 option: 60 vendor-class  50:58:45:43:6c:69:65:6e:74
> dnsmasq-dhcp: 2055027002 sent size: 17 option: 97 client-machine-id  00:00:00:00:00:00:00:00:00:00:00:0c:c4:7a...
> dnsmasq-dhcp: 2055027002 sent size:  7 option: 43 vendor-encap  47:04:80:00:00:00:ff
> dnsmasq-tftp: error 0 TFTP Aborted received from 10.101.0.82
> dnsmasq-tftp: failed sending /var/lib/tftpboot/undionly.kpxe.0 to 10.101.0.82
> dnsmasq-tftp: sent /var/lib/tftpboot/undionly.kpxe.0 to 10.101.0.82
> dnsmasq-dhcp: 2213580070 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 2213580070 vendor class: PXEClient:Arch:00000:UNDI:002001
> dnsmasq-dhcp: 2213580070 user class: iPXE
> dnsmasq-dhcp: 2213580070 PXE(enp2s0f0) 0c:c4:7a:7d:39:3a proxy
> dnsmasq-dhcp: 2213580070 tags: ipxe, enp2s0f0
> dnsmasq-dhcp: 2213580070 broadcast response
> dnsmasq-dhcp: 2213580070 sent size:  1 option: 53 message-type  2
> dnsmasq-dhcp: 2213580070 sent size:  4 option: 54 server-identifier  10.101.0.94
> dnsmasq-dhcp: 2213580070 sent size:  9 option: 60 vendor-class  50:58:45:43:6c:69:65:6e:74
> dnsmasq-dhcp: 2213580070 sent size: 17 option: 97 client-machine-id  00:00:00:00:00:00:00:00:00:00:00:0c:c4:7a...
> dnsmasq-dhcp: 2213580070 sent size: 28 option: 43 vendor-encap  06:01:03:0a:04:00:50:58:45:08:07:80:01:01...
> dnsmasq-dhcp: 2213580070 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 2213580070 vendor class: PXEClient:Arch:00000:UNDI:002001
> dnsmasq-dhcp: 2213580070 user class: iPXE
> dnsmasq-dhcp: 0 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 0 vendor class: PXEClient:Arch:00000:UNDI:002001
> dnsmasq-dhcp: 0 user class: iPXE
> dnsmasq-dhcp: 0 PXE(enp2s0f0) 10.101.0.89 0c:c4:7a:7d:39:3a http://10.101.0.94:8080/boot.ipxe.0
> dnsmasq-dhcp: 0 tags: ipxe, enp2s0f0
> dnsmasq-dhcp: 0 bootfile name: http://10.101.0.94:8080/boot.ipxe.0
> dnsmasq-dhcp: 0 next server: 10.101.0.94
> dnsmasq-dhcp: 0 broadcast response
> dnsmasq-dhcp: 0 sent size:  1 option: 53 message-type  5
> dnsmasq-dhcp: 0 sent size:  4 option: 54 server-identifier  10.101.0.94
> dnsmasq-dhcp: 0 sent size:  9 option: 60 vendor-class  50:58:45:43:6c:69:65:6e:74
> dnsmasq-dhcp: 0 sent size: 17 option: 97 client-machine-id  00:00:00:00:00:00:00:00:00:00:00:0c:c4:7a...
> dnsmasq-dhcp: 0 sent size:  7 option: 43 vendor-encap  47:04:80:01:00:00:ff
> dnsmasq-dhcp: 2055026970 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 2055026970 vendor class: PXEClient:Arch:00000:UNDI:002001
> dnsmasq-dhcp: 2055026970 PXE(enp2s0f0) 0c:c4:7a:7d:39:1a proxy
> dnsmasq-dhcp: 2055026970 tags: enp2s0f0
> dnsmasq-dhcp: 2055026970 broadcast response
> dnsmasq-dhcp: 2055026970 sent size:  1 option: 53 message-type  2
> dnsmasq-dhcp: 2055026970 sent size:  4 option: 54 server-identifier  10.101.0.94
> dnsmasq-dhcp: 2055026970 sent size:  9 option: 60 vendor-class  50:58:45:43:6c:69:65:6e:74
> dnsmasq-dhcp: 2055026970 sent size: 17 option: 97 client-machine-id  00:00:00:00:00:00:00:00:00:00:00:0c:c4:7a...
> dnsmasq-dhcp: 2055026970 sent size: 45 option: 43 vendor-encap  06:01:03:0a:04:00:50:58:45:08:07:80:00:01...
> dnsmasq-dhcp: 2055026970 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 2055026970 vendor class: PXEClient:Arch:00000:UNDI:002001
> dnsmasq-dhcp: 2055026970 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 2055026970 vendor class: PXEClient:Arch:00000:UNDI:002001
> dnsmasq-dhcp: 2055026970 PXE(enp2s0f0) 10.101.0.81 0c:c4:7a:7d:39:1a undionly.kpxe.0
> dnsmasq-dhcp: 2055026970 tags: enp2s0f0
> dnsmasq-dhcp: 2055026970 bootfile name: undionly.kpxe.0
> dnsmasq-dhcp: 2055026970 next server: 10.101.0.94
> dnsmasq-dhcp: 2055026970 sent size:  1 option: 53 message-type  5
> dnsmasq-dhcp: 2055026970 sent size:  4 option: 54 server-identifier  10.101.0.94
> dnsmasq-dhcp: 2055026970 sent size:  9 option: 60 vendor-class  50:58:45:43:6c:69:65:6e:74
> dnsmasq-dhcp: 2055026970 sent size: 17 option: 97 client-machine-id  00:00:00:00:00:00:00:00:00:00:00:0c:c4:7a...
> dnsmasq-dhcp: 2055026970 sent size:  7 option: 43 vendor-encap  47:04:80:00:00:00:ff
> dnsmasq-tftp: error 0 TFTP Aborted received from 10.101.0.81
> dnsmasq-tftp: failed sending /var/lib/tftpboot/undionly.kpxe.0 to 10.101.0.81
> dnsmasq-tftp: sent /var/lib/tftpboot/undionly.kpxe.0 to 10.101.0.81
> dnsmasq-dhcp: 717195627 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 717195627 vendor class: PXEClient:Arch:00000:UNDI:002001
> dnsmasq-dhcp: 717195627 user class: iPXE
> dnsmasq-dhcp: 717195627 PXE(enp2s0f0) 0c:c4:7a:7d:39:1a proxy
> dnsmasq-dhcp: 717195627 tags: ipxe, enp2s0f0
> dnsmasq-dhcp: 717195627 broadcast response
> dnsmasq-dhcp: 717195627 sent size:  1 option: 53 message-type  2
> dnsmasq-dhcp: 717195627 sent size:  4 option: 54 server-identifier  10.101.0.94
> dnsmasq-dhcp: 717195627 sent size:  9 option: 60 vendor-class  50:58:45:43:6c:69:65:6e:74
> dnsmasq-dhcp: 717195627 sent size: 17 option: 97 client-machine-id  00:00:00:00:00:00:00:00:00:00:00:0c:c4:7a...
> dnsmasq-dhcp: 717195627 sent size: 28 option: 43 vendor-encap  06:01:03:0a:04:00:50:58:45:08:07:80:01:01...
> dnsmasq-dhcp: 717195627 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 717195627 vendor class: PXEClient:Arch:00000:UNDI:002001
> dnsmasq-dhcp: 717195627 user class: iPXE
> dnsmasq-dhcp: 0 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 0 vendor class: PXEClient:Arch:00000:UNDI:002001
> dnsmasq-dhcp: 0 user class: iPXE
> dnsmasq-dhcp: 0 PXE(enp2s0f0) 10.101.0.87 0c:c4:7a:7d:39:1a http://10.101.0.94:8080/boot.ipxe.0
> dnsmasq-dhcp: 0 tags: ipxe, enp2s0f0
> dnsmasq-dhcp: 0 bootfile name: http://10.101.0.94:8080/boot.ipxe.0
> dnsmasq-dhcp: 0 next server: 10.101.0.94
> dnsmasq-dhcp: 0 broadcast response
> dnsmasq-dhcp: 0 sent size:  1 option: 53 message-type  5
> dnsmasq-dhcp: 0 sent size:  4 option: 54 server-identifier  10.101.0.94
> dnsmasq-dhcp: 0 sent size:  9 option: 60 vendor-class  50:58:45:43:6c:69:65:6e:74
> dnsmasq-dhcp: 0 sent size: 17 option: 97 client-machine-id  00:00:00:00:00:00:00:00:00:00:00:0c:c4:7a...
> dnsmasq-dhcp: 0 sent size:  7 option: 43 vendor-encap  47:04:80:01:00:00:ff
> dnsmasq-dhcp: 3702913799 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 3702913799 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 674134305 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 674134305 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 2790246778 available DHCP subnet: 10.101.0.1/255.255.255.0
> dnsmasq-dhcp: 2790246778 available DHCP subnet: 10.101.0.1/255.255.255.0

docker logs for bootcfg container:
> 2016-06-21 20:43:23.199742 I | main: starting bootcfg HTTP server on 0.0.0.0:8080
> 2016-06-21 20:43:50.516862 D | api: HTTP GET /boot.ipxe
> 2016-06-21 21:43:53.301044 D | api: HTTP GET /boot.ipxe.0
> 2016-06-21 21:43:53.316829 D | api: HTTP GET /ipxe?uuid=00000000-0000-0000-0000-0cc47a7cc03a&mac=0c-c4-7a-7c-c0-3a&domain=ppc.lan&hostname=&serial=S105224
> 2016-06-21 21:44:03.694881 D | api: HTTP GET /boot.ipxe.0
> 2016-06-21 21:44:03.710521 D | api: HTTP GET /ipxe?uuid=00000000-0000-0000-0000-0cc47a7d393a&mac=0c-c4-7a-7d-39-3a&domain=ppc.lan&hostname=&serial=SC06718
> 2016-06-21 21:44:15.732488 D | api: HTTP GET /boot.ipxe.0
> 2016-06-21 21:44:15.748042 D | api: HTTP GET /ipxe?uuid=00000000-0000-0000-0000-0cc47a7d391a&mac=0c-c4-7a-7d-39-1a&domain=ppc.lan&hostname=&serial=SC06698

Thanks for reading - any insight appreciated.

**Comment by mark-casey** [comment]
Some things I forgot:
- Up until recently there was a doc page about using real hardware (seems to have been removed). While I had to update a few of the flags in the docker run for bootcfg to newer formats and copy ./examples/assets to ./assets I was able to get the "pxe-to-ram-booted" type example on that page to work. I'm not sure if the extra dhcp leases were appearing then too, or not.
- In this current situation, the hosts do not seem to be be pxe booting at all (or else I'd be tempted to ignore the temporary extra leases).

**Comment by dghubble** [comment]
A machine with PXE firmware will broadcast once and be served `undionly.kpxe` and again with iPXE to obtain the next boot server. In proxy mode, dnsmasq does not allocate IP addresses, your DHCP server does.

One thing you might test, from a console, when iPXE starts ctrl+B to use the interpreter and run `dhcp` manually a few times to see the results. You can stop dnsmasq during this testing, since its not involved in the host <-> DHCP server.

The docs about real hardware should be covered by https://github.com/coreos/coreos-baremetal/blob/master/Documentation/network-setup.md and https://github.com/coreos/coreos-baremetal/blob/master/Documentation/deployment.md#deployment. The libvirt examples can be used with real hardware, you'll just need to modify the MAC address selectors and IPs. Feel free to open issues if some guide is missing that you'd like to see.

> the hosts do not seem to be be pxe booting at all

Can you get a console to one of the hosts and get an error message? If you have a spare host on the same network, can it:

* `curl http://10.101.0.94:8080/boot.ipxe`
* `curl http://10.101.0.94:8080/ipxe`
* `curl http://10.101.0.94:8080/ignition`

One thing to lookout for, profile's have to refer back to bootcfg to load different sorts of configs and the examples use `bootcfg.foo:8080` which works for the tutorials. On a real network, you'll want to point to your bootcfg instance, `10.101.0.94:8080`. Better yet, use a DNS name `provisioner.myinternal.com`.

https://github.com/coreos/coreos-baremetal/blob/master/examples/profiles/pxe-disk.json#L9

**Comment by mark-casey** [comment]
> One thing to lookout for, profile's have to refer back to bootcfg to load different sorts of configs and the examples use bootcfg.foo:8080 which works for the tutorials. On a real network, you'll want to point to your bootcfg instance, 10.101.0.94:8080. Better yet, use a DNS name provisioner.myinternal.com.
> 
> https://github.com/coreos/coreos-baremetal/blob/master/examples/profiles/pxe-disk.json#L9

This was definitely part of the problem. In the past when I'd succeeded pxe booting to ram I assume it just didn't run the "ssh.yaml" Ignition file (since I didn't have the location set right then either) and went on as best it could.

I've also found that the triplicate lease problem is that my DHCP server considers the request to have come from a new client if the clientid isn't the same as an existing entry (AND that the router's GUI had a bug that was not correctly showing me that each of each host's 3 entries had a different clientid). A host with the mac address `0C:C4:7A:7C:C0:3A` resulted in DHCP leases with these clientids:

  - `1:c:c4:7a:7c:c0:3a`
  - `0:0:0:0:0:0:0:0:0:0:0:c:c4:7a:7c:c0:3a`
  - `ff:b6:22:f:eb:0:2:0:0:ab:11:42:6a:8a:7f:61:93:e2:d9`

So do the iPXE broadcast and the pulling down Ignition config look like DHCP requests? Perhaps if I only pass mac addresses to bootcfg and not a uuid it would be happier?

In any case the hosts are pxe booting on both examples now and I can totally live with letting the extra leases expire on their own, since the booted OS will not be fluctuating in the clientid it uses.

Thanks for the help! Any thoughts on the couple questions above are appreciated but I'm going to go ahead and close.
