### ISSUE TITLE
Machine config does not match mac address if entry in data directory contains uppercase characters

### ISSUE THREAD

**Issue by wktmeow** [coreos/coreos-baremetal#25]
Not sure if this is intended or not.  I put in the machine data with upper case characters in the mac address and was scratching my head for a few minutes about why it wouldn't match.  Would be cool if it could match regardless of case, or alternatively a reminder to use lowercase in the docs

**Comment by dghubble** [comment]
With 2dd017e, the YAML input parser considers machine attributes (e.g. "mac", "MAC") reserved for hardware matching so special validation can be performed on those to ensure MAC addresses are normalized according to `net.HardwareAddr`.

Going forward, the server will reject user-defined non-normalized MAC addresses with a helpful message. In contrast, all valid machine reported MAC addresses are accepted to account for hardware variations. This should solve your issue.

**Comment by wktmeow** [comment]
Great, thanks a lot!
