### ISSUE TITLE
Bootcfg: /ignition endpoint should support retries

### ISSUE THREAD

**Issue by colhom** [coreos/coreos-baremetal#272]
If a profile lists an `ignition_id` that does not (yet) exist, `/ignition` endpoint should support returning a 202 HTTP response to the requester. This will indicate to the ignition instance that it's config is not yet ready, and that it should retry. 

I propose also adding a boolean field to the Profiles object to configure this behavior:

```
"id" : "etcd"
"ignition_id" : "etcd.yaml",

"allowRetry" : true
```

`allowRetry=false` would indicate that a `404` should be returned if the ignition template file does not exist. `allowRetry=true` will result in a `202`. 

ref / depends on https://github.com/coreos/bugs/issues/1458

\cc @dghubble 

PS - The spec says for HTTP status `202`:

> The entity returned with this response SHOULD include an indication of the request's current status and either a pointer to a status monitor or some estimate of when the user can expect the request to be fulfilled.

I think we can wait on this.

**Comment by dghubble** [comment]
I'm not sure I understand the use case, so I'd like to know more. If a config template (be that a Fuze/Ignition template, Cloud-config template, or generic template) is referenced by a machine profile, but not present in the appropriate `/var/lib/bootcfg/{cloud,ignition,generic}` location, that's incomplete declarative data about what machines should do.

Example of referencing an non-existing template:

```
[44806.683946] bootcfg[5]: time="2016-07-12T17:08:38Z" level=info msg="No Ignition or Fuze template named: k8s-meister.yaml" group=node1 group_name="k8s controller" labels=map[mac:52:54:00:a1:9c:ae] profile=k8s-master
```

Ignition (agent) will already retry for a short time when it receives 404's, then drop to an emergency shell. So currently we could debug the missing template by looking at either `bootcfg`'s logs or Ignition's journal logs.

You'd like Ignition to block/retry indefinitely if a 202 is received in the hopes the operator might add the file to avoid a reboot? But then `bootcfg` logs are the only way for an operator to spot the mis-configuration and I'm not sure how its much better than Ignition's current retry strategy?

**Comment by colhom** [comment]
@dghubble the goal is to be able to define a machine's bootcfg profile _after_ that machine has already POST'ed and started the boot process. On many providers, choice pieces of metadata (private IP, mac address, disk uuid, etc) are not available until after the machine has started booting.

I want a way for bootcfg to tell ignition: "wait, your configuration is still coming" for amounts of time on the order of 10's of minutes to a handful of hours.  

The general case is: There is a long running operation that needs to happen after the machine boots, but before (a portion of) it's ignition config is generated.

In addition, it would be nice to make this waiting state explicit vs a bootcfg misconfiguration. I feel: 
* 404 ~=  _I don't have this currently, and have no reason to expect I will_ .
* 202 ~=  _I don't have this currently, but I expect to in the future_.

**Comment by dghubble** [comment]
> On many providers, metadata (private IP, mac address, disk uuid, etc) are not available until after the machine has started booting

But Ignition supports various platform metadata services or you can write custom metadata services for the purposes of loading such information at Ignition runtime. https://coreos.com/ignition/docs/latest/metadata.html.

If you don't know a MAC address or another hardware label, there is not enough information to match a request anyway. You'd have to have a default matcher which makes all client machines retry indefinitely when templates are missing.

**Comment by colhom** [comment]
> If you don't know a MAC address or another hardware label, there is not enough information to match a request anyway.

Mac address was bad example. Solid examples are:
* Assign-on-create IP addresses
* Randomly generated hostnames, DNS names, machine identifiers
* External volume ids assigned on boot

I agree that, in the situation that the coreos-metadata service supports the data you want from your provider (which is definitely is not always true), this type of behavior is not necessary. 

In addition, there is much-desired flexibility gained by being able to dynamically and arbitrarily generate ignition configs based on post-boot metadata, and not necessarily locking yourself in to coreos-metadata's simple substitution interface for supported variables.

**Comment by dghubble** [comment]
I'm not particularly interested in adding this feature. Its mainly for the rare cloud provider that coreos-metadata doesn't yet support (e.g. Packet in this case). I'd rather we slowly add Ignition support for those providers/platforms and in the mean time, have the host introspect and populate a /run/metadata file which will be similar to what Ignition will do when the provider is supported.

If you really want this behavior, you could do it yourself when doing CoreOS installs. Have a default group (no selectors) with a profile with an Ignition config like [install-reboot](https://github.com/coreos/coreos-baremetal/blob/master/examples/ignition/install-reboot.yaml#L23). Tweak the curl to a loop to keep retrying for a particular machine's Ignition config for as long as you like or as long as it normally takes you to manually go add a configuration.

**Comment by colhom** [comment]
@dghubble I'm going to go ahead and just close this out. I'm in agreement.
