### ISSUE TITLE
missing coreos/dnsmasq container image

### ISSUE THREAD

**Issue by philips** [coreos/coreos-baremetal#28]
See the image referenced here: https://github.com/coreos/coreos-baremetal/tree/master/examples#network-environment

I assume this should be "quay.io/coreos/dnsmasq" and that we need to upload that image?

**Comment by dghubble** [comment]
It's under dockerfiles/dnsmasq. The full docs link to it and the examples README should too. We could upload it as well, it is quite minimal.
