### ISSUE TITLE
Default to mounting /var/log in kubelet-wrapper

### ISSUE THREAD

**Issue by chancez** [coreos/coreos-baremetal#288]
https://coreos.com/kubernetes/docs/latest/kubelet-wrapper.html#use-the-cluster-logging-add-on

I've helped quite a few people who are using coreos-baremetal who've ran into issues with clustered logging. We already mount in the host's `resolv.conf`, maybe in addition we should default to mounting in `/var/log` so the logging addon works without any changes.

@dghubble what do you think?

**Comment by dghubble** [comment]
Yeah, should be fine. In the old days kublet would fill up whatever disk space it was given, but it should be smarter now. Still would be nice if kubelet documented its operational guarantees.

**Comment by dghubble** [comment]
Closed by #296
