### ISSUE TITLE
docs: consistent naming of bootcfg service

### ISSUE THREAD

**Issue by philips** [coreos/coreos-baremetal#30]
It is referenced as "server", "api", and "config service" at various points. Perhaps it would be best to just come up with a globally unique name like: coreos-boot-server?

**Comment by dghubble** [comment]
Increasingly, I've started calling this the Config Service (perhaps `config-server`?) to describe the role of serving/rendering/verifying configs to machines' network boot programs and early "provision" tools like ignition/cloud-init. At this point, we can use the config service to boot and/or provision different kernels so I can see coreos in the name pigeonholing use cases. I'm open to whatever though.

**Comment by dghubble** [comment]
I'm all in on calling this `bootcfg` and the corresponding CLI `bootctl`.

**Comment by dghubble** [comment]
Fixed in ed584de9cc7. `bootcfg` should be used everywhere in place of "server" and "config service".
