### ISSUE TITLE
Support YAML groups/profiles

### ISSUE THREAD

**Issue by urzds** [coreos/coreos-baremetal#304]
It would be nice if bootcfg would again support YAML groups and profiles. Valid JSON is hard to generate, while YAML can be generated more easily from simple templates.

E.g. when building a group config file, JSON is harder to generate:
```json
{
  "thearray": [
    "element1",
    "element2"
  ]
}
```
than YAML, because one does not have to deal with preventing trailing commata:
```yaml
thearray:
- element1
- element2
```

**Comment by dghubble** [comment]
From IRC:

My aim is for the bootcfg objects (profiles, groups, ...) to have a single JSON representation in the store (filesystem, etc). Those objects can be written by hand in /var/lib/bootcfg (typical case today) but problems like with commas are best addressed by higher level tools talking to the gRPC API (the CLI, graphical apps, etc.) That's not to say the CLI couldn't allow YAML as the input type potentially. `bootcmd group create -f mygroup.yaml` but at the storage layer I'd avoid YAML.

**Comment by dghubble** [comment]
If it would be helpful, I can see a case for the CLI allowing a YAML format, similar to how Kubernetes does. That should be a separate issue. Any interest in adding it since I can't prioritize that for a while?

```
bootcmd group create -f mygroup.yaml
```

**Comment by urzds** [comment]
* The implementation should use CoreOS' Fuze for conversion? If not, what other YAML-to-JSON conversion library do you (CoreOS) use usually?
* How do you usually deal with different formats? Try different parsers until one succeeds (I'd call that the Unix style), and if none succeeds, output the parsing errors of all of them? Or do you just use the parser that is associated with the file extension (which I would call the Windows style)?
