### ISSUE TITLE
"error parsing Ignition config: unrecognized keys: [enable enable command content]"

### ISSUE THREAD

**Issue by urzds** [coreos/coreos-baremetal#308]
bootcfg logged "error parsing Ignition config: unrecognized keys: [enable enable command content]". The "enable" key is valid in several places and I cannot spot any place where I am using it in an invalid place. It would be great, if bootcfg could print the whole path (e.g. `systemd/units[1]/dropins[1]/content`) to the invalid key.

**Comment by dghubble** [comment]
Can you the Fuze config with redactions? Does it correspond to https://github.com/coreos/fuze/blob/master/doc/configuration.md?

Fuze YAML to Ignition transformation and validation is done by the [Fuze](https://github.com/coreos/fuze) package. This should be raised as a feature request there. Fuze doesn't enable issues, so file them at https://github.com/coreos/bugs

**Comment by urzds** [comment]
Meanwhile I figured out that networkd units cannot be enabled as systemd units can. `command` was a remainder of an incomplete conversion from cloud-config and `content` should have been `contents`.

I filed a feature request at coreos/bugs#1504 as you suggested.
