### ISSUE TITLE
question on fleet and ignition

### ISSUE THREAD

**Issue by khanattlab** [coreos/coreos-baremetal#316]
in using the examples directory for a basic ipxe 3 machine cluster, fleet unit is not loaded.  Is it just missing in the files or is not needed? Am new to ignition so please bear with me.
Also can I just add the ssh key for user core directly in the ignition file? thanks

**Comment by khanattlab** [comment]
Actually- I just realized the example is just for an etcd cluster- I guess I could add fleet and other units.
thanks

**Comment by dghubble** [comment]
At v0.3.0, the etcd cluster example had fleet. But fleet isn't strictly needed so the unit was removed. https://github.com/coreos/coreos-baremetal/blob/d4afc6ae97778d3a6009d5cb01b0963012c6e29c/examples/ignition/etcd.yaml
