### ISSUE TITLE
docker service fails in rktnetes clusters

### ISSUE THREAD

**Issue by dghubble** [coreos/coreos-baremetal#329]
Edit: rktnetes clusters on CoreOS Alpha 1051.0.0 (with docker 1.12).

rel: https://github.com/coreos/coreos-kubernetes/pull/642

**Comment by pbx0** [comment]
Only clusters created via scripts in about a 13 day window between these PRs: 
- coreos/coreos-kubernetes#551
- coreos/coreos-kubernetes#642

**Comment by dghubble** [comment]
For coreos-baremetal then, this only affects rktnetes clusters. Those clusters operate correctly without docker, though its unexpected.

**Comment by dghubble** [comment]
Fixed in https://github.com/coreos/coreos-baremetal/pull/332
