### ISSUE TITLE
Ignition config example from documentation makes a service fail

### ISSUE THREAD

**Issue by simoninkin** [coreos/coreos-baremetal#339]
I am currently fighting my way through CoreOS's sometimes broken documentation and this trouble made me waste yet another 2h of my time. Maybe I can spend a few more minutes to help somebody else save this time.

Basically, check these out:
https://coreos.com/blog/introducing-ignition.html
https://github.com/coreos/ignition/blob/master/doc/examples.md

Both of them have an example with a systemd unit config:

`[Unit]\nConditionFirstBoot=yes\n\n[Service]\nType=oneshot\nExecStart=/usr/bin/unzip /home/core/coreos_production_image_pcr_policy.zip -d /home/core\n\n[Install]\nWantedBy=multi-user.target`

Unfortunatelly, the '\n' symbols make systemd fail the service with an error message: "Invalid section header". If you simply specify the config as follows (removing the \n's), the service starts without a hiccup:

```
[Unit]
ConditionFirstBoot=yes

[Service]
Type=oneshot
ExecStart=/usr/bin/unzip /home/core/coreos_production_image_pcr_policy.zip -d /home/core

[Install]
WantedBy=multi-user.target
```
Please fix the docs.

Thanks,
Simon

**Comment by crawford** [comment]
Newline literals are not valid JSON. The blog post you are referring to is demonstrating how to use Ignition. I get the sense that you are not actually using this tool directly. How are you creating these unit files?

The documentation for Ignition: https://coreos.com/ignition

**Comment by simoninkin** [comment]
Yeah, you were right. I used single quotes in a PHP script to generate the config. Of course it put literal \n in the string...

**Comment by crawford** [comment]
https://coreos.com/validate/ is a great tool for validating the output of your PHP scripts.
