### ISSUE TITLE
Coreos REBOOT_STRATEGY=off not work

### ISSUE THREAD

**Issue by xianxian0703** [coreos/coreos-baremetal#347]
cat /etc/coreos/update.conf 
GROUP=stable
REBOOT_STRATEGY=off

cat /etc/os-release 
NAME=CoreOS
ID=coreos
VERSION=1122.2.0
VERSION_ID=1122.2.0
BUILD_ID=2016-09-06-1449
PRETTY_NAME="CoreOS 1122.2.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

Coreos  REBOOT_STRATEGY=off not work , I need help 
Coreos  REBOOT_STRATEGY=off not work , I need help 
Coreos  REBOOT_STRATEGY=off not work , I need help

**Comment by dghubble** [comment]
Locksmith coordinates reboots after updates, you're turning that part off. `update-engine.service` can still download updates to be used on next boot; there are other sources for the reboot.

https://github.com/coreos/bugs/issues/161
