### ISSUE TITLE
Boot order and avoiding an install loop

### ISSUE THREAD

**Issue by AlexRRR** [coreos/coreos-baremetal#349]
Hello,

I've been trying really hard to understand how `bootkube-install` example should work, the problem I have right now it that I am stuck in a loop with at the os installing stage. Here is how I understand the flow:

1. The server boots via ipxe and then calls the bootcfg service in my case ```http://cloud-config.internaldomain.com/boot.ipxe```
2. As the `install.json` file in Groups does not contain a selector and the other files in the `groups` do (`mac`  & `os`) it applies the `install-reboot.yaml` ignition config then proceeds to boot and adds the `installer.service` unit file.
3. This unit file installs CoreOS to disk using the `coreos-install` utility and then reboots.
```bash
         #!/bin/bash -ex
          curl "{{.ignition_endpoint}}?{{.request.raw_query}}&os=installed" -o ignition.json
          coreos-install -d /dev/sda -C {{.coreos_channel}} -V {{.coreos_version}} -i ignition.json {{if index . "baseurl"}}-b {{.baseurl}}{{end}}
          udevadm settle
          systemctl reboot
```
4. Goto Step 1.

How does the `os` selector works? how is my server expected to get out of this loop as at boot it will never send the`os=installed` parameter? I know I am clearly missing something very obvious and would really appreciate some help.

Cheers,

Alex.

**Comment by dghubble** [comment]
Servers with BMCs are configured with a disk first, network second boot order. 

If, later, you would like to force a machine which is booting from disk to reprovision itself with some new role, set the boot device to use for the next boot,

    ipmitool -H machine.domain.com -U x -P x chassis bootdev pxe

power cycle,

ipmitool -H machine.domain.com -U x -P x power reset

and whatever `bootcfg` Profile matches the machine will be used.

For little desktop boxes without BMC's for remote boot order changes (a few of my machines are like this) I use the `install-shutdown` Profile. After CoreOS installs to disk and powers off, you can go through and change them to boot from disk. I have some more clever plans as well if you're in this situation.

**Comment by AlexRRR** [comment]
Aha! Thanks so much for taking the time answer, now that makes a lot of sense, I was expecting things to be completely administrator-less.

We have a different setup where we boot from network first and then disk. With our old Debian + PXE system it would boot a pxelinux menu, with some install options and then after a timeout of a few secs it would boot from disk. 

I think I will take this approach as it would be easier to select from a menu item like _Apply bootcfg profile_ when I want to repurpose the server, instead of messing with ipmitools or the bmc.

Thanks so much for the explanation.

Alex.

**Comment by dghubble** [comment]
Sure thing, we have a network which uses an iPXE menu with many existing options and delegation to bootcfg was added as one of the choices like you're describing so it works in that role too.

Later, I'd like the `bootcfg` gRPC API to support iPXE/GRUB enabling or disabling fallback to disk so this can be powered by client tools in any language, the graphical interface, or a machine database.

**Comment by dimm0** [comment]
How does this work with coreos self-update feature? I see my nodes updating themselves and becoming not accessible because they're not getting the ignition config anymore.
I'm using the tectonic cluster.

**Comment by dghubble** [comment]
Most likely, your machines are configured to PXE boot every time. I have a bare-metal requirements document for Tectonic, but it seems to be missing from the website - lemme see what's up.

**Comment by dimm0** [comment]
The nodes only PXE-boot to install, then boot from the disk.
It worked fine until CoreOS decided to upgrade. I found the machines stuck in boot menu. When I pressed enter, they booted and upgraded, but I lost all the settings including the ssh key.

**Comment by dghubble** [comment]
Hm, that doesn't sound right. Can you file an issue on https://github.com/coreos/bugs/issues showing CoreOS version before/after, update-engine, boot logs, and Ignition logs? Thanks.

**Comment by dimm0** [comment]
Ok, will do
