### ISSUE TITLE
Update k8s/rkt versions for rktnetes

### ISSUE THREAD

**Issue by Quentin-M** [coreos/coreos-baremetal#353]
As soon as Kubernetes 1.4 is officially released (stable), we should update the versions used for rktnetes.

See https://github.com/coreos/rkt/issues/2751#issuecomment-249553908.

**Comment by dghubble** [comment]
Yes, rkt v1.14.0 is needed for practical rktnetes use. https://github.com/dghubble/metal/commit/6a246825ffc32a36d0653cff5ec551019857924b
