### ISSUE TITLE
Broken link in Documentation/getting-started-docker.md

### ISSUE THREAD

**Issue by jpwarren** [coreos/coreos-baremetal#376]
In the Containers section of getting-started-docker.md:
- The etcd groups link yields a 404 not found error

Also, the links to e.g. node1's ipxe are active links in github, but they appear to be designed to be clicked when you've started up a local bootcfg in a Docker container on the same machine you're accessing github from.

Maybe consider changing this doco to use a curl commandline and make it obvious that you're helping the user see what an endpoint on their bootcfg server looks like?

**Comment by dghubble** [comment]
^ fixed/clarified both links
