### ISSUE TITLE
how to pass kernel args on second boot?

### ISSUE THREAD

**Issue by khrisrichardson** [coreos/coreos-baremetal#401]
@dghubble in a toy environment, I have an issue accessing an SDHCI PCI root device unless I pass some kernel args. This is not a problem on first boot, but I am not sure how to append kernel args on second boot (e.g. bootkube-install vs. bootkube).

I have tried a couple things in ignition/install-reboot.yaml to edit the grub.cfg file following coreos-install, but to no avail. Obviously adding options to /etc/modprobe.d is a non-starter.

Any tips? Thanks.

P.S. - great work, and matchstick is a great name.

**Comment by dghubble** [comment]
When you PXE boot, an Ignition config can be used to install to disk and then modify the grub.cfg afterward. I think you have the right idea, and just need an example. I recall the quoting being tricky.

```
/usr/bin/mount /dev/disk/by-label/OEM /mnt
echo set linux_append=\\"coreos.config.url=\"{{.ignition_endpoint}}\"\\" > /mnt/grub.cfg
```

This was how the Ignition config for the first boot from disk was set in the past, before we gave the `coreos-install` script a handy `-i` flag:

https://github.com/coreos/coreos-baremetal/blob/35f24eb720e30a8cc18af390c3e6db274356cc31/examples/ignition/coreos-install.yaml#L15

**Comment by dghubble** [comment]
Btw, we've been saying first pxe boot (pxe kernel args) and first boot from disk (grub kernel args). Ignition runs in both cases, since first PXE boot is kinda just for disk installs and the first boot from disk is where more of the provisioning work is done.

On the second and subsequent boots, Ignition will not run.

**Comment by khrisrichardson** [comment]
I will give this a shot. Thanks for the pointers.
