### ISSUE TITLE
bootcfg does not render kernel args

### ISSUE THREAD

**Issue by fischerman** [coreos/coreos-baremetal#406]
I have a single profile which looks like the following:
```
{
  "id": "gw",
  "name": "gw",
  "boot": {
    "kernel": "/assets/coreos/1185.3.0/coreos_production_pxe.vmlinuz",
    "initrd": ["/assets/coreos/1185.3.0/coreos_production_pxe_image.cpio.gz"],
    "args": [
      "coreos.autologin"
    ]
  },
  "ignition_id": "gw.yaml"
}
```

The machine successfully boots, however it ignore the autologin flag. I've noticed that the iPXE endpoint does not render the kernel args as specified in the profile. `http://10.1.1.253:8080/ipxe?mac=12:91:88:65:cd:d1` returns:
```
#!ipxe
kernel /assets/coreos/1185.3.0/coreos_production_pxe.vmlinuz
initrd /assets/coreos/1185.3.0/coreos_production_pxe_image.cpio.gz 
boot
```
I run bootcfg with docker (quay.io/coreos/bootcfg:v0.4.2)
Am I missing something?

**Comment by crawford** [comment]
It looks like you are referring to the documentation for master instead of the specific version you are using. `args` is not supported in v0.4.2 (it was added later). You'll need to use `cmd` instead.

**Comment by fischerman** [comment]
That did the trick. Thank you!
