### ISSUE TITLE
Problem with ESXi

### ISSUE THREAD

**Issue by amiri27** [coreos/coreos-baremetal#412]
Hi,

I had a problem with using Bootcfg inside esxi deployment. As I see after booting from image it didn't try to install coreos on disk..
I copied install.json inside /var/lib/bootcfg/groups as well as install-reboot profiles and ignition in their correct path..
Should I do something else or could you please mention how to troubleshoot this error?

Regards,

**Comment by amiri27** [comment]
As I see on vmware esxi it didn't try to install coreos on disk and everytime I restart the newly created VM it will try to boot again from ipxe..

**Comment by amiri27** [comment]
I have this error on my bootcfg logs:

time="2017-01-09T10:21:29Z" level=error msg="error rendering template: template: :7:29: executing \"\" at <.ssh_authorized_keys>: range can't iterate over ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEA5JGeCHkjSQ65vf/eAg/evz3iSozO+yirr0ko7foJHiEgklnZijLAR85eY2wNHC+2H3cgKx
smRNYrJC6xwbDc4LUzOrH0Ce/P0K36a/x+jFTHPPg9Qs69147sBcB2FPn/ChTJtFpVJ7W2r6X/6AiL2lTErxxQcaWzKxiy7tFtA6TtfyqYkJiHrU5n24+cf5foqyeV73gbdJIV8igmOduiVYGCXBcblgi1bo5kJKi3od4D/D
fr965Rlhr5fqY6XeIYHc4BUMKQXkfgGT7pZ9PNIOBM84FDAC7CZH/r8eA7fErUmMH/UNb0r2kXMR8g+RRK4fP9qkxQAs1vBajqip2BIw=="

**Comment by dghubble** [comment]
Can you SSH or console to the box and `journalctl -u installer` please. You can see from [install-reboot](https://github.com/coreos/coreos-baremetal/blob/master/examples/ignition/install-reboot.yaml#L4) Ignition that an install to `/dev/sda` will be attempted.

**Comment by amiri27** [comment]
Hi..

As I mentioned up there's no attempt to install on box :( on bootcfg there's no log which show any request send to download ignition. Check the bellow log:

Jan 09 10:51:27 bootcfg.zarinpal.name rkt[31982]: [ 8095.041602] bootcfg[5]: time="2017-01-09T10:51:27Z" level=info msg="HTTP GET /boot.ipxe"
Jan 09 10:51:27 bootcfg.zarinpal.name rkt[31982]: [ 8095.047356] bootcfg[5]: time="2017-01-09T10:51:27Z" level=info msg="HTTP GET /ipxe?uuid=2ff74d56-c873-29d0-526b-46c
715ecd232&mac=00-0c-29-ec-d2-32&domain=&hostname=&serial=VMware-56%204d%20f7%202f%2073%20c8%20d0%2029-52%206b%2046%20c7%2015%20ec%20d2%2032"
Jan 09 10:51:27 bootcfg.zarinpal.name rkt[31982]: [ 8095.047903] bootcfg[5]: time="2017-01-09T10:51:27Z" level=debug msg="Matched an iPXE config" labels=map[serial:VMwa
re-56 4d f7 2f 73 c8 d0 29-52 6b 46 c7 15 ec d2 32 uuid:2ff74d56-c873-29d0-526b-46c715ecd232 mac:00:0c:29:ec:d2:32 domain: hostname:] profile=install-reboot
Jan 09 10:51:27 bootcfg.zarinpal.name rkt[31982]: [ 8095.049544] bootcfg[5]: time="2017-01-09T10:51:27Z" level=info msg="HTTP GET /assets/coreos/1235.4.0/coreos_product
ion_pxe.vmlinuz"
Jan 09 10:52:10 bootcfg.zarinpal.name rkt[31982]: [ 8138.172298] bootcfg[5]: time="2017-01-09T10:52:10Z" level=info msg="HTTP GET /assets/coreos/1235.4.0/coreos_product
ion_pxe_image.cpio.gz"

After downloading files to the box there's no try to get more information from bootcfg server.

Regards,

**Comment by dghubble** [comment]
Are you setting kernel args to make use of an Ignition config? Example clusters show profiles with [args](https://github.com/coreos/coreos-baremetal/blob/d5c5dde2e43429600fcd64533327308e0df115b7/examples/profiles/install-reboot.json#L8) and its covered [here](https://github.com/coreos/coreos-baremetal/blob/d5c5dde2e43429600fcd64533327308e0df115b7/Documentation/ignition.md#reference) in Ignition docs.

**Comment by amiri27** [comment]
As I see there's a difference between the master and the your example. Your example key is cmdline but the master key is args.

https://github.com/coreos/coreos-baremetal/blob/d5c5dde2e43429600fcd64533327308e0df115b7/examples/profiles/install-reboot.json#L7

https://github.com/coreos/coreos-baremetal/blob/master/examples/profiles/install-reboot.json#L7

When I try to download /ipxe here's the output:

```
#!ipxe
kernel /assets/coreos/1235.4.0/coreos_production_pxe.vmlinuz
initrd /assets/coreos/1235.4.0/coreos_production_pxe_image.cpio.gz 
boot
```

I see there's no command need to be run after boot

**Comment by dghubble** [comment]
Ah. The examples on master are for master, which makes use of the new `args` field. [This] has not been included in a tagged release.

You'll want to look at the examples corresponding to your bootcfg version, which use `cmdline`.

**Comment by amiri27** [comment]
Thanks @dghubble for your help.. more than 2days we working to solve this problem and finally fixed..

I have another question regarding dnsmasqu which is that everytime I restart a machine the IP is changing.. How can I solve this problem?

Regards,

**Comment by amiri27** [comment]
@dghubble a new problem started to show up.. As soon as installation finishes, coreos restart the machine and there's no problem.. But if we do a restart on server we will see FSCK error 8 and coreos crash.. how can we troubleshoot this problem?

**Comment by dghubble** [comment]
DHCP servers can allocate static IPs to particular MAC addresses. `dnsmasq` can do this too, check `contrib/dnsmasq` [examples](https://github.com/coreos/coreos-baremetal/blob/master/contrib/dnsmasq/metal0.conf#L6). If you have `coreos-install` script or fs/partition problems, can you please ask on coreos/bugs?

Closing as the original issue using `bootcfg` has been resolved by using examples which correspond to the release version. Also updating the title for Google-ability.
