### ISSUE TITLE
Link to dnf/yum repo serving 404

### ISSUE THREAD

**Issue by josephjacks** [coreos/coreos-baremetal#418]
https://github.com/coreos/coreos-baremetal/blob/master/Documentation/deployment.md#rpm-based-distro

**Comment by dghubble** [comment]
There is a README announcement that coreos-baremetal and bootcfg are being renamed to CoreOS matchbox, which will be reflected in v0.5.0. Earlier releases are still available by the bootcfg name. See #400.

Please keep using the the rpm-based-install [doc](https://github.com/coreos/coreos-baremetal/blob/v0.4.2/Documentation/deployment.md#rpm-based-distro) from the v0.4.* tagged releases.

```
dnf copr enable dghubble/bootcfg
dnf install bootcfg

# requires yum-plugin-copr
yum copr enable dghubble/bootcfg
yum install bootcfg
```

Hope that clarifies and I'll get the new RPM repo name setup soon!

**Comment by josephjacks** [comment]
Thanks!
