### ISSUE TITLE
coreos groundless reboots

### ISSUE THREAD

**Issue by port22** [coreos/coreos-baremetal#58]
This now happened multiple times to me, still with version 835.12 on KVM, standalone coreos:
```
Feb 16 14:30:52 myserver.de update_engine[601]: <request protocol="3.0" version="CoreOSUpdateEngine-0.1.0.0" updaterversion="CoreOSUpdateEngine-0.1.0.0" installsource="scheduler" ismachine="1">
Feb 16 14:30:52 myserver.de update_engine[601]: <os version="Chateau" platform="CoreOS" sp="835.12.0_x86_64"></os>
Feb 16 14:30:52 myserver.de update_engine[601]: <app appid="{e96281a6-d1af-4bde-9a0a-97b76e56dc57}" version="835.12.0" track="stable" bootid="{47abeb90-1ff6-4aaf-a61f-cbdb1fb7e503}" oem="" oemversio
Feb 16 14:30:52 myserver.de update_engine[601]: <ping active="1"></ping>
Feb 16 14:30:52 myserver.de update_engine[601]: <updatecheck></updatecheck>
Feb 16 14:30:52 myserver.de update_engine[601]: <event eventtype="3" eventresult="2" previousversion=""></event>
Feb 16 14:30:53 myserver.de update_engine[601]: [0216/143053:INFO:libcurl_http_fetcher.cc(297)] Transfer completed (200), 267 bytes downloaded
Feb 16 14:30:53 myserver.de update_engine[601]: [0216/143053:INFO:omaha_request_action.cc(574)] Omaha request response: <?xml version="1.0" encoding="UTF-8"?>
Feb 16 14:30:53 myserver.de update_engine[601]: <response protocol="3.0" server="update.core-os.net">
Feb 16 14:30:53 myserver.de update_engine[601]: <daystart elapsed_seconds="0"></daystart>
Feb 16 14:30:53 myserver.de update_engine[601]: <app appid="e96281a6-d1af-4bde-9a0a-97b76e56dc57" status="ok">
Feb 16 14:30:53 myserver.de update_engine[601]: <updatecheck status="noupdate"></updatecheck>
Feb 16 14:30:53 myserver.de update_engine[601]: </app>
Feb 16 14:30:53 myserver.de update_engine[601]: </response>
Feb 16 14:30:53 myserver.de update_engine[601]: [0216/143053:INFO:action_processor.cc(68)] ActionProcessor::ActionComplete: OmahaResponseHandlerAction action failed. Aborting processing.
Feb 16 14:30:59 myserver.de systemd[1]: locksmithd.service: Service hold-off time over, scheduling restart.
Feb 16 14:31:19 myserver.de locksmithd[8776]: Reboot strategy is "off" - shutting down.
Feb 16 14:31:28 myserver.de systemd-logind[602]: Power key pressed.
Feb 16 14:31:28 myserver.de systemd-logind[602]: Powering Off...
Feb 16 14:31:28 myserver.de systemd-logind[602]: System is powering down.
```

1) As I understand, update_engine asks for update. Response: no update.
2) Locksmith schedules restart: Aborts because REBOOT_STRATEGY=off
3) then, anything walks in and sends an ACPI signal to shutdown (it actually reboots)

I did reinstall coreos multiple times and my cloud-config is rather simple.

**Comment by dghubble** [comment]
Can you verify the contents of `/etc/coreos/update.conf` and the output of `locksmithctl status`? Reboot strategy "off" is for applying the update on the next reboot and then you're sending a shutdown signal which looks expected. What is your desired behavior?

**Comment by port22** [comment]
> then you're sending a shutdown signal which looks expected

I send nothing. That's the problem. I don't want the machine to reboot or update automatically. So who is the ghost pressing the power button? 

```
$ cat /etc/coreos/update.conf 
GROUP=stable
REBOOT_STRATEGY=off
```
> Reboot strategy "off" is for applying the update on the next reboot
Of course, the update downloads, and the next boot occurs with the vmlinuz_b. 
But reboot_strategy=off is, I thought, for not rebooting after a downloaded upgrade ...

I currently stopped locksmithctl and update_client -services. Hope that prevents it, but anyway that's a strange behaviour OR I understand something wrong

**Comment by dghubble** [comment]
I mentioned this to the os team earlier. The locksmith messaging is unclear: `locksmithd[8776]: Reboot strategy is "off" means locksmith is exiting, not that it is triggering a shutdown (first commit in https://github.com/coreos/locksmith/pull/101/commits).

I'm not sure about the origin of your shutdown signal.

**Comment by port22** [comment]
me neither, that's my problem :D 

But I must admit that I am misusing coreos here, of course. I know, coreos is for massive deployments at cluster-level and I am running a single instance with manual upgrades. But it's actually for prevalidating if coreos is suitable for my production case and the cluster part is not even in testing scope for now. 

Anyway, you don't want to loose nodes without a reason, even if you have a cluster.

**Comment by croemmich** [comment]
I'm having the same issue on a cluster of 3. The logs don't seem to indicate any issues, just `Power key pressed.`

**Comment by dghubble** [comment]
Ok then, something is turning off a CoreOS host, sometimes. This might be more suitable for [coreos/bugs](https://github.com/coreos/bugs) of unknown origin or for contacting the support team to help debug on your infrastructure.

Is this repeatable?
How often does it occur?
Is it limited to a particular host?
What version(s) of CoreOS does this occur on?
Are you running on your own hardware?
Does it occur on local, virtualized hosts?

Are you using `bootcfg` to boot and configure these machines? The coreos-install profile will happily re-install CoreOS and reboot forever if you provide that profile during network boot. You'd be seeing this every few minutes, so I doubt it is that.

On hardware, perhaps there's some dead man's switch triggering shutdown?

**Comment by croemmich** [comment]
I'm running 3 8GB Linode VMs with CoreOS 835.13.0. It's repeatable in the sense that it seems to happen a couple times a week, but I haven't found a pattern yet. All three of my boxes seem to do it around the same time. They were all launched at about the same time so your dead man's switch theory is possible. Unfortunately I can't find anything fishy in the logs.

I've temporarily mitigated the problem by editing `/etc/systemd/logind.conf`:
```
[Login]
HandlePowerKey=ignore
```

**Comment by port22** [comment]
how can we make this "hack" permanent ? (how must it look like in clouc-config).

As I wrote, my coreos is on KVM (www.netcup.de), since I shutdown the locksmithd service, that problem didn't happen again.

**Comment by dghubble** [comment]
https://coreos.com/os/docs/latest/update-strategies.html shows the cloud-config for configuring disabling the reboot that should follow an update.

```
#cloud-config
coreos:
  update:
    reboot-strategy: off
```

Disabling automatic updates isn't recommended unless you're rebooting nodes yourself, frequently. 

You can stop or disable the update service and locksmith permanently if truly needed.

```
#cloud-config
coreos:
  units:
    - name: update-engine.service
      command: stop
    - name: locksmithd.service
      command: stop
```

**Comment by dghubble** [comment]
If either of you see another reboot and you're sure the reboot-strategy is off and that the power key wasn't pressed, please open an issue on [coreos/bugs](https://github.com/coreos/bugs) so we can track down the source.

Currently, this report doesn't seem specific to CoreOS deployment on baremetal or the use of `bootcfg` for bootstrapping/provisioning so I'm going to close this. I haven't seen this occur on my hardware installs.

**Comment by vcaputo** [comment]
Additionally, when locksmith causes a reboot ever since https://github.com/coreos/locksmith/commit/6ab97ac2da97028da78f00809746beee845c105b a message is broadcast with a 5 minute delay if there are any logins present.

**Comment by jumanjiman** [comment]
fwiw we had trouble with this across multiple OS a couple years ago. a BIOS update resolved it. it's probably not your issue, but just putting it out there.

**Comment by tobilg** [comment]
I have a similar problem... On of my cluster hosts just shut down with no interaction. I see this in the `sudo journalctl -xe` logs:

```
Jun 10 11:14:57 coreos-hw-node-3.group.local systemd[1]: locksmithd.service: Service hold-off time over, scheduling restart.
Jun 10 11:14:57 coreos-hw-node-3.group.local systemd[1]: Stopped Cluster reboot manager.
-- Subject: Unit locksmithd.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit locksmithd.service has finished shutting down.
Jun 10 11:14:57 coreos-hw-node-3.aic-group.local systemd[1]: Started Cluster reboot manager.
-- Subject: Unit locksmithd.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit locksmithd.service has finished starting up.
--
-- The start-up result is done.
```

Automatic updates should be disabled:

``` 
$ cat /etc/coreos/update.conf
GROUP=stable
REBOOT_STRATEGY=off
```

but I see

```
$ sudo systemctl status locksmithd
● locksmithd.service - Cluster reboot manager
   Loaded: loaded (/usr/lib64/systemd/system/locksmithd.service; disabled; vendor preset: disabled)
   Active: activating (auto-restart) since Fri 2016-06-10 11:13:05 UTC; 225ms ago
  Process: 7249 ExecStart=/usr/lib/locksmith/locksmithd (code=exited, status=0/SUCCESS)
 Main PID: 7249 (code=exited, status=0/SUCCESS)
```

`locksmithd` seems to try to start every few seconds, although I have disabled and stopped the service. What could be the reason?
