### ISSUE TITLE
uppercase mac address in requires results in "main: config: normalize MAC address ... to ..."

### ISSUE THREAD

**Issue by urzds** [coreos/coreos-baremetal#83]
When bootcfg encounters an uppercase mac address in requires, it will print `main: config: normalize MAC address ... to ...` and `exit(1)`.

This is very inconvenient. One would assume that bootcfg is able to do a simple uppercase -> lowercase conversion on the fly. Additionally, the error message is very misleading. I did not understand it is an error message for a very long time, assuming that bootcfg was normalising the mac address (as I had expected).

At the very least I would expect a "fatal error:" prefix and a message like: "MAC address ... not normalised, expecting ... instead".

**Comment by dghubble** [comment]
Related to #25
