### ISSUE TITLE
Versioned tags for bootcfg Quay.io images

### ISSUE THREAD

**Issue by urzds** [coreos/coreos-baremetal#87]
The images on Quay.io currently do not carry version tags. It would be nice if they would, so I could know for sure that the image my different machines using are everywhere the same (i.e. a specified version instead of some random "latest").

**Comment by dghubble** [comment]
But they already are? An image is built on every commit to master and tagged with the commit id or the release tag. See the entire list going back to the beginning https://quay.io/repository/coreos/bootcfg?tab=tags

Additionally, you can verify that the binary inside the tagged ACI or Docker image is the correct commit id or tag.

```
./bin/bootcfg -version
sudo rkt run coreos.com/bootcfg:v0.2.0 -- -version
sudo docker run quay.io/coreos/bootcfg:latest -version
```

Are you asking something different?

**Comment by urzds** [comment]
I was trying `docker run quay.io/coreos/bootcfg:v0.2.0`.

**Comment by dghubble** [comment]
Hmm, you're right, that release image is missing. I believe this was because the tag wasn't pushed when Travis did the build. I've added the tag to the 35f24eb720e30a8cc18af390c3e6db274356cc31 image.

Give it a shot now? Thanks for pointing that out.
