### ISSUE TITLE
Support for Ignition?

### ISSUE THREAD

**Issue by SpencerBrown** [coreos/coreos-baremetal#9]
I've been using [CoreOS Ignition](https://github.com/coreos/ignition) in my experiments with PXE booting CoreOS. I've been using dnsmasq with pxelinux. Now I found David Anderson's [pixiecore](https://github.com/danderson/pixiecore) project and then this one, which I like very much and want to use, as they greatly simplify and regularize the setup. 

However it seems that this coreos-baremetal project supports CoreOS cloud config but not Ignition. 

Have you thought about (a) is this a goal, (b) what is the priority?

I'd be willing to dive in and try to implement this, with your guidance, if you're not already working on it.

@crawford @philips interested in your input on this too.

**Comment by dghubble** [comment]
Yes, ignition support is coming soon. I'm planning for them to be served based on attributes similar to cloud configs.

There are some changes to how the data volume will be laid out and served to refine how configs are resolved and allow groups of machines to reference configs. Ignition will probably be lumped in right after that is fleshed out.

**Comment by crawford** [comment]
Support for cloud-config was a stepping stone to get this project rolling. The near-term goal is to remove support for cloud-config in favor of Ignition (since cloud-config is nearly worthless on baremetal).

**Comment by SpencerBrown** [comment]
Actually, one can simply place an Ignition JSON file in the `cloud` directory, and it works. One can't use cloud config and Ignition together, but that's OK for what I'm doing.

`machine.json`:

```json
{
    "id": "austin-01",
    "spec": {
      "boot": {
          "kernel": "/images/coreos/current/coreos_production_pxe.vmlinuz",
          "initrd": ["/images/coreos/current/coreos_production_pxe_image.cpio.gz"],
          "cmdline": {
              "coreos.config.url": "http://10.2.0.200:8080/cloud?mac=90:2b:34:14:f6:6a",
              "coreos.autologin": "",
              "coreos.first_boot": "1"
          }
      },
      "cloud_id": "pxe-ignition.json"
    },
    "spec_id": ""
}
```

**Comment by dghubble** [comment]
Yes, Content-Type detection happens to make that work. Ignition support was added in c8af7227aba902492f989d779187c3d44b1b4e61 so that would be the preferred way now.

```
{
    "id": "austin-01",
    "spec": {
      "boot": {
          "kernel": "/images/coreos/835.9.0/coreos_production_pxe.vmlinuz",
          "initrd": ["/images/coreos/835.9.0/coreos_production_pxe_image.cpio.gz"],
          "cmdline": {
              "coreos.config.url": "http://10.2.0.20:8080/ignition?uuid=${uuid}",
              "coreos.autologin": "",
              "coreos.first_boot": ""
          }
      },
      "ignition_id": "pxe-ignition.json"
    },
    "spec_id": ""
}
```

These endpoints are kept separate because the expectations around templating and substitution are different so there may be divergence of behavior.
